// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

import './App.css';
;

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  return Curry._1(setCount, (function (count) {
                                return count + 1;
                              }));
                }), 100);
          return (function (param) {
                    clearInterval(intervalId);
                    
                  });
        }), []);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("h1", {
                  className: "MyName"
                }, "Name: Phakkhamat"), React.createElement("div", {
                  className: "line"
                }, React.createElement("h2", {
                      className: "box1"
                    }), React.createElement("h2", {
                      className: "box2"
                    }), React.createElement("h2", {
                      className: "box3"
                    })), React.createElement("div", undefined, React.createElement("h2", {
                      className: "box4"
                    }), React.createElement("h2", {
                      className: "box5"
                    }), React.createElement("h2", {
                      className: "box6"
                    })), React.createElement("div", undefined, React.createElement("h2", {
                      className: "box7"
                    }), React.createElement("h2", {
                      className: "box8"
                    }), React.createElement("h2", {
                      className: "box9"
                    })));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
