// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Box$AppTemplateReasonReact from "./Box.bs.js";
import * as Name$AppTemplateReasonReact from "./Name.bs.js";

import './App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(React.StrictMode, {
                  children: React.createElement(Name$AppTemplateReasonReact.make, {})
                }), React.createElement("div", {
                  className: "line"
                }, React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "aquamarine"
                          })
                    }), React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "cyan"
                          })
                    }), React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "darkcyan"
                          })
                    })), React.createElement("div", undefined, React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "seagreen"
                          })
                    }), React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "mediumseagreen"
                          })
                    }), React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "darkseagreen"
                          })
                    })), React.createElement("div", undefined, React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "cornflowerblue"
                          })
                    }), React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "royalblue"
                          })
                    }), React.createElement(React.StrictMode, {
                      children: React.createElement(Box$AppTemplateReasonReact.make, {
                            color: "darkslateblue"
                          })
                    })));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
