// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Box(Props) {
  var color = Props.color;
  return React.createElement("h2", {
              style: {
                backgroundColor: color,
                display: "inline-flex",
                height: "50px",
                margin: "10px",
                width: "50px"
              }
            });
}

var make = Box;

var $$default = Box;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
