// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Name(Props) {
  return React.createElement("h1", {
              style: {
                borderBottomStyle: "solid",
                textAlign: "center",
                flex: "1",
                flexDirection: "column"
              }
            }, "Phakkhamat");
}

var make = Name;

var $$default = Name;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
